const EMAIL='info.kusima@gmail.com';
const mail=(s,b)=>`mailto:${EMAIL}?subject=${encodeURIComponent(s)}&body=${encodeURIComponent(b)}`;

const sources={
 law182:{label:'OFICIÁLNY',title:'Zákon č. 182/1993 Z. z.',desc:'Vlastníctvo bytov a pravidlá správy domu.',url:'https://www.slov-lex.sk/ezbierky/pravne-predpisy/SK/ZZ/1993/182/'},
 heat503:{label:'OFICIÁLNY',title:'Vyhláška č. 503/2022 Z. z.',desc:'Rozpočítavanie tepla a teplej vody.',url:'https://www.slov-lex.sk/ezbierky-fe/pravne-predpisy/SK/ZZ/2022/503/'},
 consumer:{label:'OFICIÁLNY',title:'Zákon č. 108/2024 Z. z.',desc:'Ochrana spotrebiteľa.',url:'https://www.slov-lex.sk/ezbierky/pravne-predpisy/SK/ZZ/2024/108'},
 soi:{label:'OFICIÁLNY',title:'SOI · služby spojené s bývaním',desc:'Kompetencie Slovenskej obchodnej inšpekcie.',url:'https://www.soi.sk/novinky/informacie-pre-verejnost/kompetencie-soi-v-oblasti-kontroly-sluzieb-spojenych-s-byvanim'},
 urso:{label:'OFICIÁLNY',title:'ÚRSO · tepelná energetika',desc:'Regulácia a informácie pre odberateľov tepla.',url:'https://www.urso.gov.sk/v-tepelnej-energetike/'},
 mediation:{label:'OFICIÁLNY',title:'Ministerstvo spravodlivosti · mediácia',desc:'Mimosúdne riešenie civilných a susedských sporov.',url:'https://www.justice.gov.sk/sluzby/mediacia-v-civilnom-prave/informacie-pre-obcanov/'},
 cadastre:{label:'OFICIÁLNY',title:'ESKN · kataster',desc:'List vlastníctva a katastrálne konania.',url:'https://beta.skgeodesy.sk/sk/kataster/eskn-portal/'},
 buildlaw:{label:'OFICIÁLNY',title:'Stavebný zákon č. 25/2025 Z. z.',desc:'Aktuálny rámec stavebných zásahov.',url:'https://www.slov-lex.sk/ezbierky/pravne-predpisy/SK/ZZ/2025/25/20251101'},
 siea:{label:'ODBORNÝ',title:'SIEA · obnova bytového domu',desc:'Zateplenie, okná, strecha a energetické úspory.',url:'https://www.siea.sk/bezplatne-poradenstvo/publikacie-a-prezentacie/zateplovanie-a-vymena-okien-v-bytovych-domoch/'},
 sfrb:{label:'OFICIÁLNY',title:'ŠFRB · obnova bytovej budovy',desc:'Možnosti financovania obnovy bytových domov.',url:'https://wwwold.sfrb.sk/ziadatel/obnovujte-s-nami/'},
 better:{label:'ODBORNÝ',title:'Lepšia správa · odborné články',desc:'Aktuálne témy zo správy bytových domov.',url:'https://lepsiasprava.sk/blog/'},
 annual:{label:'ODBORNÝ',title:'BytovýDom.sk · ročné vyúčtovanie',desc:'Praktický výklad, ako sa vo vyúčtovaní orientovať.',url:'https://www.bytovydom.sk/ako-sa-zorientovat-v-rocnom-vyuctovani/'}
};

const buttons={
 writeFault:`<div class="actions"><a class="btn primary" href="${mail('[KUSIMA] Porucha v dome','Prosím uveďte:\n- dom / adresu\n- miesto poruchy\n- čo presne sa deje\n- telefón\n- podľa možnosti priložte fotografiu\n')}">Napísať správcovi</a></div>`,
 writeGeneral:`<div class="actions"><a class="btn primary" href="${mail('[KUSIMA] Požiadavka vlastníka','Prosím uveďte:\n- dom / adresu\n- číslo bytu alebo priestor\n- čo potrebujete vyriešiť\n- telefón\n')}">Napísať správcovi</a></div>`
};

const nodes={
 client:{title:'Ako vám môžem pomôcť?',intro:'Vyberte, čo je vám najbližšie. Nemusíte vedieť, kam presne váš problém patrí.',choices:[['problem','Mám problém','Porucha, vyúčtovanie, susedský spor alebo iná nepríjemnosť.'],['arrange','Potrebujem niečo vybaviť','Tlačivo, zmena údajov, prevod bytu alebo potvrdenie.'],['objection','Mám výhradu','K správe, vyúčtovaniu, dodávateľovi alebo hlasovaniu.'],['proposal','Mám návrh','Oprava, úspora, nové pravidlo alebo anketa.']]},
 problem:{title:'Čo sa deje?',intro:'Vyberte najbližšiu možnosť. Ak sa netrafíte presne, nič sa nedeje.',choices:[['fault','Porucha alebo havária','Voda, výťah, dvere, osvetlenie, strecha, elektro alebo spoločné priestory.'],['billing','Vyúčtovanie alebo platba','Preplatok, nedoplatok, predpis, odpočet alebo rozpočítanie.'],['heat','Teplo, voda alebo merače','Kúrenie, teplá voda, odpočty alebo meradlá.'],['neighbors','Susedské spory','Hluk, fajčenie, konflikt alebo obťažovanie.'],['reconstruction','Sused prerába byt','Obava zo zásahu do konštrukcie alebo rozvodov.'],['otherproblem','Niečo iné','Napíšte nám stručne, čo sa deje.']]},
 arrange:{title:'Čo potrebujete vybaviť?',intro:'Cieľom je, aby ste nemuseli telefonicky zisťovať, čo od vás potrebujeme.',choices:[['sale','Predávam alebo kupujem byt','Odpočty, kontakty a zmena vlastníka.'],['change','Mením údaje alebo počet osôb','E-mail, telefón, korešpondenčná adresa alebo užívatelia.'],['forms','Potrebujem tlačivo','Vzory a dokumenty na stiahnutie.'],['myreconstruction','Chcem prerábať byt','Čo oznámiť správcovi a kedy riešiť stavebný úrad.'],['confirmation','Potrebujem potvrdenie alebo doklad','Kópia, potvrdenie, vyjadrenie alebo podklad.'],['voting','Schôdza, hlasovanie alebo splnomocnenie','Ako sa zapojiť do rozhodovania.']]},
 objection:{title:'Čo vám prekáža?',intro:'Výhrada je užitočná, ak vieme, čo konkrétne treba preveriť alebo vysvetliť.',choices:[['managercomplaint','Nie som spokojný so správou','Komunikácia, rýchlosť alebo postup správcu.'],['billcomplaint','Nesedí mi vyúčtovanie','Chcem vysvetlenie alebo kontrolu konkrétnej položky.'],['contractorcomplaint','Nie som spokojný s dodávateľom','Kvalita opravy, správanie alebo termín.'],['votecomplaint','Nesúhlasím s hlasovaním','Výsledok, postup, kvórum alebo zápisnica.']]},
 proposal:{title:'Čo navrhujete?',intro:'Dobrý nápad nemusí čakať na schôdzu. Najprv ho môžeme preveriť.',choices:[['repairproposal','Opravu alebo obnovu','Strecha, fasáda, výťah, dvere, rozvody alebo balkóny.'],['energyproposal','Úsporu energie','Zateplenie, regulácia, meranie alebo osvetlenie.'],['ruleproposal','Zmenu pravidla v dome','Spoločné priestory, poriadok alebo spôsob užívania.'],['surveyproposal','Chcem poznať názor ostatných','Rýchla anketa cez Google Forms.'],['supplierproposal','Odporúčam dodávateľa','Firma alebo remeselník, s ktorým máte dobrú skúsenosť.']]},

 fault:{type:'answer',kicker:'PORUCHA / HAVÁRIA',title:'Najprv potrebujeme vedieť, čo sa stalo a kde.',html:`<p>Ak ide o poruchu domu, správca je správna prvá adresa. Najrýchlejšie je poslať e-mail s domom, miestom poruchy, stručným popisom, telefónom a podľa možnosti fotografiou.</p><div class="notice"><strong>Pri bezprostrednom ohrození života, požiari, plyne alebo vážnej havárii nečakajte na správcu a volajte 112.</strong></div><div class="steps"><div class="step"><b>1. Kde?</b> Dom, vchod, poschodie alebo spoločný priestor.</div><div class="step"><b>2. Čo presne?</b> Nie iba „nejde výťah“, ale čo výťah robí alebo nerobí.</div><div class="step"><b>3. Kontakt a foto.</b> Ak treba vstup alebo servis, vieme sa ozvať.</div></div>${buttons.writeFault}`,src:['law182']},
 billing:{type:'answer',kicker:'VYÚČTOVANIE / PLATBY',title:'Ak niečo nesedí, potrebujeme konkrétnu položku.',html:`<p>Ročné vyúčtovanie je výsledkom viacerých nákladov, odpočtov a pravidiel rozpočítania. Najprv vysvetlíme výpočet, potom preveríme vstupné údaje.</p><div class="softnote"><b>Najlepšia otázka:</b> „Prečo je táto položka 184 €?“ namiesto „Mám vysoký nedoplatok.“</div><div class="actions"><a class="btn primary" href="${mail('[KUSIMA] Otázka k vyúčtovaniu','Prosím uveďte:\n- dom / adresu\n- číslo bytu\n- rok vyúčtovania\n- konkrétnu položku alebo sumu\n- čo podľa vás nesedí\n')}">Požiadať o vysvetlenie</a></div>`,src:['heat503','soi','annual','consumer']},
 heat:{type:'answer',kicker:'TEPLO / VODA / MERAČE',title:'Najprv rozlíšime poruchu, meranie a rozpočítanie.',html:`<p>Pri kúrení alebo vode môže byť problém technický, merací alebo účtovný. Napíšte, či ide o nefunkčné kúrenie, teplú vodu, podozrivý odpočet, merač alebo vyúčtovanie.</p><div class="steps"><div class="step"><b>Technická porucha:</b> miesto, prejav, odkedy trvá.</div><div class="step"><b>Merač:</b> odfoťte displej, označenie a typ.</div><div class="step"><b>Rozpočítanie:</b> uveďte rok a položku vyúčtovania.</div></div>${buttons.writeGeneral}`,src:['heat503','urso','siea']},
 neighbors:{type:'answer',kicker:'SUSEDIA A SPOLUNAŽÍVANIE',title:'Rozumieme, že susedský spor vie znepríjemniť bývanie.',html:`<p>Situáciu nám môžete stručne opísať. Pomôžeme vám zorientovať sa a oddeliť to, čo patrí správcovi, od osobného sporu.</p><div class="notice"><strong>Správca nie je polícia ani súd.</strong> Pri násilí, vyhrážkach alebo závažnom rušení verejného poriadku treba kontaktovať príslušné orgány.</div><div class="steps"><div class="step"><b>1. Vecný dohovor.</b> Konkrétny problém, čas a návrh riešenia.</div><div class="step"><b>2. Záznam faktov.</b> Dátum, čas, čo sa stalo, prípadne svedkovia.</div><div class="step"><b>3. Mediácia.</b> Pri dlhom konflikte môže byť rýchlejšia než spor.</div></div><div class="actions"><a class="btn primary" href="${mail('[KUSIMA] Susedský spor','Prosím uveďte:\n- kde sa problém týka\n- čo sa deje\n- ako dlho\n- čo ste už skúsili\n- čo od správcu očakávate\n')}">Opísať situáciu</a></div>`,src:['mediation','law182']},
 reconstruction:{type:'answer',kicker:'STAVEBNÉ ÚPRAVY SUSEDA',title:'Nie každá prerábka je vecou správcu. Niektoré zásahy však môžu byť.',html:`<p>Ak máte podozrenie na zásah do nosnej konštrukcie, spoločných rozvodov, fasády alebo iného spoločného prvku, napíšte nám konkrétne, čo ste spozorovali.</p><div class="notice"><strong>Správca nie je stavebný úrad.</strong> Otázky povoľovania stavebných zásahov rieši príslušný orgán podľa aktuálneho stavebného zákona.</div>${buttons.writeGeneral}`,src:['law182','buildlaw']},
 otherproblem:{type:'answer',kicker:'INÝ PROBLÉM',title:'Napíšte nám ho vlastnými slovami.',html:`<p>Nemusíte poznať správnu kategóriu. Uveďte dom, byt alebo priestor, čo sa deje a čo od správcu potrebujete.</p>${buttons.writeGeneral}`},
 sale:{type:'answer',kicker:'PREDAJ / KÚPA BYTU',title:'Pri zmene vlastníka je dôležitý správny deň a správne údaje.',html:`<p>Oznámte zmenu vlastníka a kontakty. Praktické je zachytiť stavy bytových meradiel ku dňu odovzdania bytu a ideálne ich odfotiť.</p><div class="actions"><a class="btn primary" href="${mail('[KUSIMA] Zmena vlastníka bytu','Prosím uveďte:\n- dom / adresu\n- číslo bytu\n- pôvodný a nový vlastník\n- dátum zmeny / odovzdania\n- kontakty\n- stavy meradiel\n')}">Oznámiť zmenu vlastníka</a></div>`,src:['cadastre','law182']},
 change:{type:'answer',kicker:'ZMENA ÚDAJOV',title:'Jedna krátka písomná správa nám stačí.',html:`<p>Ak meníte e-mail, telefón, korešpondenčnú adresu alebo údaje dôležité pre rozpočítanie služieb, pošlite nám zmenu e-mailom.</p>${buttons.writeGeneral}`,src:['law182']},
 forms:{type:'answer',kicker:'TLAČIVÁ A VZORY',title:'Malá knižnica dokumentov, nie skládka súborov.',html:`<p>Tlačivá rozdelíme podľa životnej situácie. Zdrojom bude jeden priečinok na Google Drive, takže web bude vždy ukazovať aktuálne verzie.</p><div class="placeholder"><b>GOOGLE DRIVE · pripravované prepojenie</b><span>Prevod bytu · zmena údajov · splnomocnenie · reklamácia · súhlas · žiadosť · ďalšie vzory.</span></div>`},
 myreconstruction:{type:'answer',kicker:'REKONŠTRUKCIA VLASTNÉHO BYTU',title:'Najprv si overte, či zasahujete iba do svojho bytu.',html:`<p>Maľovanie a podlaha sú niečo iné než zásah do nosnej konštrukcie, rozvodov, fasády alebo balkóna. Ak si nie ste istí, pošlite nám stručný popis prác.</p>${buttons.writeGeneral}`,src:['law182','buildlaw']},
 confirmation:{type:'answer',kicker:'POTVRDENIE / DOKLAD',title:'Napíšte, čo presne potrebujete a na aký účel.',html:`<p>Ak neviete názov dokumentu, opíšte účel: predaj bytu, banka, kataster, poisťovňa, súd alebo vlastná evidencia.</p>${buttons.writeGeneral}`},
 voting:{type:'answer',kicker:'HLASOVANIE A SCHÔDZA',title:'O spoločnom majetku rozhodujú vlastníci.',html:`<p>Správca pripravuje podklady a proces, ale rozhodovanie patrí vlastníkom podľa zákonných pravidiel.</p><div class="softnote"><b>Naša ambícia:</b> vysvetliť hlasovanie tak, aby každý vedel, o čom rozhoduje, koľko to stojí a čo bude nasledovať.</div><div class="placeholder"><b>GOOGLE FORMS</b><span>Výborné na nezáväzné ankety a zisťovanie názoru. Záväzné hlasovanie musí rešpektovať zákonnú formu.</span></div>`,src:['law182','better']},
 managercomplaint:{type:'answer',kicker:'VÝHRADA K SPRÁVCOVI',title:'Napíšte nám ju priamo a konkrétne.',html:`<p>Uveďte, čo ste žiadali, kedy a čo sa podľa vás nestalo. Ak sme urobili chybu, chceme ju vedieť nájsť. Ak ide o vec mimo kompetencie správcu, vysvetlíme prečo.</p>${buttons.writeGeneral}`,src:['law182','soi','consumer']},
 billcomplaint:{type:'answer',kicker:'VÝHRADA K VYÚČTOVANIU',title:'Nesúhlas treba premeniť na kontrolovateľnú otázku.',html:`<p>Označte položku, sumu, odpočet alebo spôsob rozpočítania, s ktorým nesúhlasíte.</p>${buttons.writeGeneral}`,src:['heat503','soi','annual']},
 contractorcomplaint:{type:'answer',kicker:'DODÁVATEĽ / OPRAVA',title:'Odlíšime nedorobok, reklamáciu a nespokojnosť s priebehom.',html:`<p>Napíšte, čo bolo predmetom práce, čo je podľa vás zlé a pridajte fotografiu. Pri reklamácii je konkrétny popis vady najdôležitejší.</p>${buttons.writeGeneral}`},
 votecomplaint:{type:'answer',kicker:'VÝHRADA K HLASOVANIU',title:'Nesúhlas s výsledkom nie je to isté ako chyba postupu.',html:`<p>Ak máte pochybnosť o hlasovaní, napíšte presne, či namietate otázku, doručenie, kvórum, započítanie hlasu alebo zápisnicu.</p><div class="notice"><strong>Správca nemôže svojvoľne zmeniť platné rozhodnutie vlastníkov.</strong></div>${buttons.writeGeneral}`,src:['law182','better']},
 repairproposal:{type:'answer',kicker:'NÁVRH NA OPRAVU / OBNOVU',title:'Čo získame, koľko to stojí a kto o tom rozhodne?',html:`<p>Pošlite stručný návrh. Preveríme technický zmysel, rozsah, financovanie a pri väčšej investícii pripravíme podklady pre vlastníkov.</p>${buttons.writeGeneral}`,src:['law182','sfrb','better']},
 energyproposal:{type:'answer',kicker:'ENERGETICKÁ ÚSPORA',title:'Najlepšia úspora je tá, ktorú vieme zmerať.',html:`<p>Zateplenie, regulácia, izolácia rozvodov, okná alebo osvetlenie môžu dávať zmysel. Najprv technické údaje, potom návrh, cena a očakávaný efekt.</p>${buttons.writeGeneral}`,src:['siea','sfrb','urso']},
 ruleproposal:{type:'answer',kicker:'PRAVIDLÁ DOMU',title:'Najprv si overíme, či o tom vôbec môže dom rozhodnúť.',html:`<p>Nie každé želanie väčšiny sa dá premeniť na pravidlo. Niektoré veci patria vlastníkom, iné obci, polícii alebo vyplývajú priamo zo zákona.</p>${buttons.writeGeneral}`,src:['law182','better']},
 surveyproposal:{type:'answer',kicker:'ANKETA / ZISŤOVANIE NÁZORU',title:'Tu bude Google náš kôň.',html:`<p>Ak netreba hneď právne záväzné hlasovanie, vieme rýchlo zistiť názor vlastníkov cez Google Forms. Odpovede sa zbierajú do Google Sheets a výsledok vieme prehľadne zobraziť.</p><div class="notice"><strong>Anketa nie je automaticky zákonné hlasovanie.</strong> Použijeme ju na prieskum alebo prípravu rozhodnutia.</div><div class="placeholder"><b>GOOGLE FORMS · pripravované prepojenie</b><span>Aktívne ankety sa budú dať zapínať a vypínať bez zásahu do kódu.</span></div>`,src:['law182','better']},
 supplierproposal:{type:'answer',kicker:'ODPORÚČANIE DODÁVATEĽA',title:'Dobré kontakty sú cenné. Odporúčanie však nie je automatická objednávka.',html:`<p>Pošlite názov firmy alebo remeselníka, kontakt a s čím máte osobnú skúsenosť. Pri zákazke domu sa aj tak posudzuje cena, rozsah, záruka a vhodnosť.</p>${buttons.writeGeneral}`}
};

let historyStack=[];
function startClient(){document.getElementById('home').classList.remove('active');document.getElementById('dialogView').classList.add('active');historyStack=[];renderNode('client')}
function goHome(){document.getElementById('dialogView').classList.remove('active');document.getElementById('home').classList.add('active');historyStack=[];scrollTo(0,0)}
function renderNode(id,push=true){if(push&&historyStack.at(-1)!==id)historyStack.push(id);const n=nodes[id],c=document.getElementById('content');document.getElementById('crumbs').textContent=breadcrumb();if(n.type==='answer'){c.innerHTML=`<div class="answer"><span class="kicker">${n.kicker||''}</span><h3>${n.title}</h3>${n.html||''}${renderSources(n.src||[])}<p class="fine">Pracovný koncept KUSIMA. Právne citlivé texty budeme pri finálnej verzii priebežne kontrolovať podľa aktuálneho znenia predpisov.</p></div>`}else{c.innerHTML=`<h2>${n.title}</h2><p class="intro">${n.intro||''}</p><div class="options">${n.choices.map(x=>`<button class="choice" onclick="renderNode('${x[0]}')"><strong>${x[1]}</strong><span>${x[2]}</span><span class="arrow">Pokračovať →</span></button>`).join('')}</div>`}scrollTo(0,0)}
function renderSources(ids){if(!ids.length)return'';return`<div class="sources"><h4>Overené externé zdroje</h4><div class="sourcegrid">${ids.map(id=>{const s=sources[id];return`<a class="source" target="_blank" rel="noopener" href="${s.url}"><span class="badge">${s.label}</span><strong>${s.title} ↗</strong><span>${s.desc}</span></a>`}).join('')}</div></div>`}
function goBack(){if(historyStack.length<=1){goHome();return}historyStack.pop();renderNode(historyStack.at(-1),false)}
function breadcrumb(){if(!historyStack.length)return'';return'KLIENT  /  '+historyStack.slice(1).map(id=>nodes[id].type==='answer'?nodes[id].kicker:nodes[id].title).join('  /  ')}
function tick(){const d=new Date(),days=['nedeľa','pondelok','utorok','streda','štvrtok','piatok','sobota'],months=['januára','februára','marca','apríla','mája','júna','júla','augusta','septembra','októbra','novembra','decembra'];document.getElementById('clock').textContent=d.toLocaleTimeString('sk-SK',{hour:'2-digit',minute:'2-digit',second:'2-digit'});document.getElementById('date').textContent=days[d.getDay()]+' '+d.getDate()+'. '+months[d.getMonth()]}
tick();setInterval(tick,1000);